blank_issues_enabled : false

contact_links:
    -   name: "Bug report"
        about: "Report bugs with Garry's Mod here"
        url: "https://github.com/Facepunch/garrysmod-issues/issues/new/choose"

    -   name: "Facepunch support"
        about: "The official Facepunch customer support portal for game issues."
        url: "https://support.facepunchstudios.com/"

    -   name: "Official Discord server"
        about: "The official Discord server for discussing the game, as well as community help with playing or modding the game"
        url: "https://discord.gg/gmod"
