blank_issues_enabled : false

contact_links:

    -   about : I want to report a bug
        name: 🪳 Bug Report
        url : https://github.com/Facepunch/garrysmod-issues
        
    -   about : "I need support for Garry's Mod"
        name : 🚨 Support Request
        url : https://support.facepunchstudios.com/

    -   about : "I want to talk about Garry's Mod"
        name : 💬 Community Discussions
        url : https://discord.gg/gmod
