
name: Feature request
about: Suggest an idea for Garry's Mod
title: ''
labels: ''
assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        Please search existing requests, including closed ones, before opening a new request!
        If you wish to report a bug, please visit https://github.com/Facepunch/garrysmod-issues
  - type: textarea
    id: the-request
    attributes:
      label: Description
      description: Please describe your idea below.
      placeholder: Your idea goes here
    validations:
      required: true
